services:
  - type: web
    name: personatrip-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false